language: node_js

node_js:
- '8'
- '6'
- '4'
- '10'

services: docker

cache:
  directories:
  - "$HOME/.yarn-cache"

before_install: yarn global add greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update
- npm run compile

script: npm test

after_script: greenkeeper-lockfile-upload

after_success: npm run codecov

jobs:
  include:
  - stage: build docker image
    if: branch = master AND type = push
    node_js: '6'
    script:
    - yarn install --production
    - npm pack
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [ -n "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; elif [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then echo "latest"; fi`
    - docker build -t $TRAVIS_REPO_SLUG:$COMMIT .
    - if [ -n "$TAG" ]; then echo "Tagging $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:$TAG" && docker tag $TRAVIS_REPO_SLUG:$COMMIT $TRAVIS_REPO_SLUG:$TAG && docker push $TRAVIS_REPO_SLUG; fi
    after_script: skip
    after_success: skip
  - stage: npm release
    if: branch = master AND type = push
    node_js: '6'
    script: echo 'Deploying to npm ...'
    after_script: skip
    after_success: skip
    deploy:
      provider: npm
      email: git@jwr.vc
      api_key:
        secure: K/+dVjtCqesr5E5EMZo/qBdKlWwPpZ60yp1GtKoAhSZUtL4VY4A8LOJmcSeIeYvsPkK8PRSCyb2FTDfSTYEO4dWVfNPoLxWp7U48iIiHSfLdNixfTiBHyjdKdP/6oCz3TNfb9upPUb1lcb5h+rM2KJgCLT6s30Vbajka6STeDCs=
      on:
        tags: true
        repo: jamesramsay/hercule

env:
  global:
  - secure: LwDKnmYY2dPXAuvXAxxCSVFsqKIHwRJ3+vX8UClw7cEhpkZk3I2SVUsL9PWH+4d6OpWIQqFlcNHMlepNEjUA7b4DCfk2aWwxsCdEZgCu4jciuvAvb2/DGDHrggTt5OVEMM55fl/XHSleiIyJe185Vh4TKGdj26POEvm1deQaPAs=
  - secure: cxZVYUizgZPMQswzVMPT2y3UNcmKd6s77AAYa1d5thrizJEm4Zp5cM1nsEWpS09PG86JUrGWoLlf2+SVg8S8k0rL8OjZbW1XYpfuH/CRxt1AuGLA2V3gDWI707lGvyvpl5axIOS8IY4mS41chcVuNWHSEdRnWRD9RKl/esFaV8w=
  - COMMIT=${TRAVIS_COMMIT::8}
