language: node_js
node_js:
- '5'
- '4'
- '0.12'
- '0.10'
sudo: false
before_install:
# https://github.com/npm/npm/issues/11283
- npm set progress=false
- npm -g install npm@latest
- npm run install-bats
before_script:
- npm run compile
- npm run browserify
script:
- npm test
after_success:
- npm run codecov
deploy:
  provider: npm
  email: git@jwr.vc
  api_key:
    secure: K/+dVjtCqesr5E5EMZo/qBdKlWwPpZ60yp1GtKoAhSZUtL4VY4A8LOJmcSeIeYvsPkK8PRSCyb2FTDfSTYEO4dWVfNPoLxWp7U48iIiHSfLdNixfTiBHyjdKdP/6oCz3TNfb9upPUb1lcb5h+rM2KJgCLT6s30Vbajka6STeDCs=
  on:
    tags: true
    repo: jamesramsay/hercule
