// Generated by CoffeeScript 1.8.0
(function() {
  var transcludeGrammar;

  transcludeGrammar = "start\n  = f:file ' '? o:arg* {\n      return {\n        \"file\": f.value,\n        \"overrides\": o\n      };\n    }\n\narg\n  = left:placeholder ':' right:override ' '? {\n      return {\n        \"placeholder\": left,\n        \"type\": right.type,\n        \"value\": right.value\n      };\n    }\n\nplaceholder\n  = p:[a-zA-Z0-9]+ {\n      return p.join(\"\");\n    }\n\noverride\n  = file / string / reset\n\nfile\n  = f:[^ \"]+ {\n      return {\n        \"type\": \"file\",\n        \"value\": f.join(\"\")\n      };\n    }\n\nstring\n  = '\"' s:([^\"]+) '\"' {\n      return {\n        \"type\": \"string\",\n        \"value\": s.join(\"\")\n      };\n    }\n\nreset\n  = {\n      return {\n        \"type\": \"string\",\n        \"value\": \"\"\n      };\n    }";

  module.exports = {
    transcludeGrammar: transcludeGrammar
  };

}).call(this);
