#!/bin/bash
set -e

# Shell script to compute code coverage even after the Babel transforms have
# been applied.

# Clear previous coverage.
rm -rf coverage

# Generate test coverage based on however `npm test` performs the tests.
./node_modules/.bin/nyc --reporter=json ./node_modules/.bin/ava

# Move generated JSON file so it can be remapped and won't confuse Istanbul
# later.
mv coverage/coverage-final.json coverage/coverage.json

# Rewrite the coverage file taking the Babel source maps into account.
./node_modules/.bin/remap-istanbul -i coverage/coverage.json -o coverage/coverage.json

# Generate an lcov.info file and an HTML report, and output a text report.
./node_modules/.bin/istanbul report lcov text
