#!/usr/bin/env bash
#
# Script to initialize repo
# - install required node packages
# - install git hooks


node=`which node 2>&1`
if [ $? -ne 0 ]; then
  echo "Please install NodeJS."
  echo "http://nodejs.org/"
  exit 1
fi

npm=`which npm 2>&1`
if [ $? -ne 0 ]; then
  echo "Please install NPM."
fi


echo "Installing required npm packages..."
npm install

echo "Installing git hooks..."
ln -sf commit-msg .git/hooks/commit-msg
ln -sf pre-commit .git/hooks/pre-commit
