#!/bin/zsh

function lint () {
  OUTPUT=$(git diff --name-only | grep -E '(.js)$')
  a=("${(f)OUTPUT}")
  if [ -z "$a" ]; then
    exit 0
  fi
  echo $a
  e=$(./node_modules/.bin/eslint $a)
  echo $e
  if [[ "$e" != *"0 problems"* ]]; then
    echo "ERROR: Check eslint hints."
    exit 1 # reject
  fi
}
lint
